// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' 
   show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdazb1aLmpjzCb8Vovxsjdg5xxeqt8XhE',
    appId: '1:496781538316:web:5ed3df4fcc08e3f48e2a29',
    messagingSenderId: '496781538316',
    projectId: 'chat-app-cf346',
    authDomain: 'chat-app-cf346.firebaseapp.com',
    storageBucket: 'chat-app-cf346.appspot.com',
    measurementId: 'G-0WC3E1NK1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBij83HQcbjt1zdyR7bMqyHYAKnVmiY964',
    appId: '1:496781538316:android:93a53a9c5fced6aa8e2a29',
    messagingSenderId: '496781538316',
    projectId: 'chat-app-cf346',
    storageBucket: 'chat-app-cf346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6pHH744pHxWvkZLVawbIGH1ZJIyL5rg',
    appId: '1:496781538316:ios:8b9cf8e14ebb88b48e2a29',
    messagingSenderId: '496781538316',
    projectId: 'chat-app-cf346',
    storageBucket: 'chat-app-cf346.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF6pHH744pHxWvkZLVawbIGH1ZJIyL5rg',
    appId: '1:496781538316:ios:cf0f8df202e865528e2a29',
    messagingSenderId: '496781538316',
    projectId: 'chat-app-cf346',
    storageBucket: 'chat-app-cf346.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
